### ISSUE TITLE
on-click="open" isn't generated for iron-icon / folder name

### ISSUE THREAD

**Issue by isabelacmor** [winhowes/file-list#3]
<img width="701" alt="screen shot 2016-01-13 at 2 19 13 pm" src="https://cloud.githubusercontent.com/assets/4714094/12305107/17d9cd1c-ba01-11e5-80c9-f2036ce3bab1.png">

Both my iron-list and folder name are "clickable", but do not have the same on-click="open" attribute like https://github.com/winhowes/file-list/blob/master/file-list.html#L130

Is this something I need to manually set? I'm not sure how, since all the code is generated dynamically.

**Comment by winhowes** [comment]
The `on-click` is parsed out by polymer to attach an event handler to the element. So though it looks like an attribute on the element - it's not really. There's more details here: https://www.polymer-project.org/1.0/docs/devguide/events.html#annotated-listeners
